language: python

python:
  - 2.6
  - 2.7
  - pypy

install:
  - pip install --use-mirrors coveralls
  - pip install --use-mirrors nose

script: coverage run --source=stackstrap setup.py nosetests

after_success:
  coveralls
